In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets
from sklearn import metrics
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pickle

In [2]:
data = pd.read_csv('Group_9_data_cleaned.csv')
data.head(3)
# removing a redundant column
df = data.drop(['Unnamed: 0'],axis=1)
df.head()

current_1     current_2  current_3  current_4     current_5  current_6  \
0 -3.014600e-07  8.260300e-06  -0.000012  -0.000002 -1.438600e-06  -0.000021   
1  2.913200e-06 -5.247700e-06   0.000003  -0.000006  2.778900e-06  -0.000004   
2 -2.951700e-06 -3.184000e-06  -0.000016  -0.000001 -1.575300e-06   0.000017   
3 -1.322600e-06  8.820100e-06  -0.000016  -0.000005 -7.282900e-07   0.000004   
4 -6.836600e-08  5.666300e-07  -0.000026  -0.000006 -7.940600e-07   0.000013   

   current_7  current_8  current_9  current_10  ...  current_40  current_41  \
0   0.031718   0.031710   0.031721   -0.032963  ...    -0.63308      2.9646   
1   0.030804   0.030810   0.030806   -0.033520  ...    -0.59314      7.6252   
2   0.032877   0.032880   0.032896   -0.029834  ...    -0.63252      2.7784   
3   0.029410   0.029401   0.029417   -0.030156  ...    -0.62289      6.5534   
4   0.030119   0.030119   0.030145   -0.031393  ...    -0.63010      4.5155   

   current_42  current_43  current_44  current_45  current_46  current_47  \
0      8.1198     -1.4961     -1.4961     -1.4961     -1.4996     -1.4996   
1      6.1690     -1.4967     -1.4967     -1.4967     -1.5005     -1.5005   
2      5.3017     -1.4983     -1.4983     -1.4982     -1.4985     -1.4985   
3      6.2606     -1.4963     -1.4963     -1.4963     -1.4975     -1.4975   
4      9.5231     -1.4958     -1.4958     -1.4958     -1.4959     -1.4959   

   current_48  output  
0     -1.4996       1  
1     -1.5005       1  
2     -1.4985       1  
3     -1.4976       1  
4     -1.4959       1  

[5 rows x 49 columns]

In [3]:
#shape of the data 
# The data has 58509 rows 
# The data has 49 features 
df.shape

(58509, 49)

In [4]:
# statistics of the data 
df.describe()

current_1     current_2     current_3     current_4     current_5  \
count  58509.000000  5.850900e+04  5.850900e+04  5.850900e+04  5.850900e+04   
mean      -0.000003  1.756436e-06  1.111802e-06 -9.722586e-07  1.775487e-06   
std        0.000008  3.199783e-05  1.520782e-04  7.956279e-06  3.234750e-05   
min       -0.000021 -6.427550e-05 -2.937900e-04 -1.887580e-05 -6.547550e-05   
25%       -0.000007 -1.444400e-05 -7.239600e-05 -5.417500e-06 -1.475300e-05   
50%       -0.000003  8.804600e-07  5.137700e-07 -1.059100e-06  7.540200e-07   
75%        0.000002  1.877700e-05  7.520000e-05  3.554700e-06  1.906200e-05   
max        0.000015  6.860850e-05  2.965940e-04  1.701300e-05  6.978450e-05   

          current_6     current_7     current_8     current_9    current_10  \
count  5.850900e+04  58509.000000  58509.000000  58509.000000  58509.000000   
mean  -7.457535e-07      0.002854      0.002849      0.002849     -0.006349   
std    1.490893e-04      0.033692      0.033700      0.033701      0.050735   
min   -2.915565e-04     -0.086972     -0.087041     -0.086978     -0.111281   
25%   -7.379100e-05     -0.019927     -0.019951     -0.019925     -0.032144   
50%   -1.659300e-07      0.013226      0.013230      0.013247     -0.015566   
75%    7.138600e-05      0.024770      0.024776      0.024777      0.020614   
max    2.891515e-04      0.069125      0.069130      0.069131      0.099751   

       ...    current_40    current_41    current_42    current_43  \
count  ...  58509.000000  58509.000000  58509.000000  58509.000000   
mean   ...     -0.650427      5.730645      7.702923     -1.500891   
std    ...      0.100670      5.781169      4.347205      0.003629   
min    ...     -0.902350     -0.596830      0.320660     -1.510950   
25%    ...     -0.715470      1.450300      4.436300     -1.503300   
50%    ...     -0.661710      3.301300      6.479100     -1.500300   
75%    ...     -0.573980      8.288500      9.857500     -1.498200   
max    ...     -0.361745     18.545800     17.989300     -1.490550   

         current_44    current_45    current_46    current_47    current_48  \
count  58509.000000  58509.000000  58509.000000  58509.000000  58509.000000   
mean      -1.500915     -1.500809     -1.497787     -1.497814     -1.497710   
std        0.003640      0.003600      0.003002      0.002984      0.002988   
min       -1.511200     -1.510700     -1.504700     -1.504550     -1.504450   
25%       -1.503400     -1.503200     -1.499600     -1.499600     -1.499500   
50%       -1.500300     -1.500300     -1.498100     -1.498100     -1.498000   
75%       -1.498200     -1.498200     -1.496200     -1.496300     -1.496200   
max       -1.490400     -1.490700     -1.491100     -1.491350     -1.491250   

             output  
count  58509.000000  
mean       6.000000  
std        3.162305  
min        1.000000  
25%        3.000000  
50%        6.000000  
75%        9.000000  
max       11.000000  

[8 rows x 49 columns]

In [5]:
# There are 11 different classes in the output data 
# which are from 1 to 11 classes 
df['output'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [6]:
# Checking for the number of each output class labels 
# It is a blanced multi class dataset with each class is having equal number of output labels 
df['output'].value_counts()


1     5319
2     5319
3     5319
4     5319
5     5319
6     5319
7     5319
8     5319
9     5319
10    5319
11    5319
Name: output, dtype: int64

# classification - Linear model- SGD classifier

In [7]:
# Dividing input and output labels
X = df.drop(['output'],axis=1)
y = df['output']


In [8]:
# importing Min Max scalar for the data transformation
# Scaling is very important in the case of linear regression
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_X = scaler.fit_transform(X)
print(scaled_X)

[[0.5730026  0.54585804 0.47811763 ... 0.375      0.375      0.36742424]
 [0.66228185 0.44420547 0.50328617 ... 0.30882353 0.30681818 0.29924242]
 [0.49939872 0.45973556 0.47065977 ... 0.45588235 0.45833333 0.45075758]
 ...
 [0.41869175 0.62362286 0.32534757 ... 1.         1.         1.        ]
 [0.45803432 0.73932528 0.         ... 0.84558824 0.85984848 0.85984848]
 [0.33549635 0.87696412 0.62036912 ... 0.75       0.75378788 0.76893939]]


In [9]:
# dividing the dataset into train,test and validation sets
X_train, X_rem, y_train, y_rem  = train_test_split(scaled_X, y, train_size = 0.5, random_state = 100)
X_valid, X_test, y_valid, y_test = train_test_split(X_rem, y_rem, test_size = 0.5, random_state = 100)

In [10]:
# The shape of training dataset
print(f" The input training  data shape is {X_train.shape}")
print(f" The  output training data shape is {y_train.shape}")
print(f" The input validation  data shape is {X_valid.shape}")
print(f" The  output validation data shape is {y_valid.shape}")
# The shape of the test dataset 
print(f" The input testing  data shape is {X_valid.shape}")
print(f" The  output testing data shape is {y_valid.shape}")

 The input training  data shape is (29254, 48)
 The  output training data shape is (29254,)
 The input validation  data shape is (14627, 48)
 The  output validation data shape is (14627,)
 The input testing  data shape is (14627, 48)
 The  output testing data shape is (14627,)


In [11]:
from sklearn.metrics import confusion_matrix, classification_report, recall_score, accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

In [15]:
random = SGDClassifier()
random.fit(X_train,y_train)
y_train_pred = random.predict(X_train)
y_valid_pred = random.predict(X_valid)
y_test_pred  = random.predict(X_test)

### Accuracies for the random model


In [16]:
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred)}")
print(f" The validation data accuracy for the best model is {accuracy_score(y_valid,y_valid_pred)}")
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred)}")
      

 The training data accuracy for the best model is 0.6593286388186231
 The validation data accuracy for the best model is 0.6515348328433719
 The testing data accuracy for the best model is 0.6579163248564397


### Hyper parameter tuning with grid search


In [21]:
from sklearn.model_selection import cross_val_score, GridSearchCV, RandomizedSearchCV
#Hyperparameters
grid = {
    'alpha': [1e-4, 1e-3, 1e-2, 1e-1, 1e0, 1e1, 1e2, 1e3], # learning rate
    'loss': ['log'], 
    'penalty': ['l2'],
    'n_jobs': [-1]
}

sgd_cls = SGDClassifier()
gs = GridSearchCV(sgd_cls,                    # model
                   param_grid = grid,   # hyperparameters
                   scoring='accuracy',        # metric for scoring
                   cv=5)                  # number of folds
gs.fit(X_valid,y_valid)   


C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:163: FutureWarning: The loss 'log' was deprecated in v1.1 and will be removed in version 1.3. Use `loss='log_loss'` which is equivalent.
  warnings.warn(
C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:163: FutureWarning: The loss 'log' was deprecated in v1.1 and will be removed in version 1.3. Use `loss='log_loss'` which is equivalent.
  warnings.warn(
C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:163: FutureWarning: The loss 'log' was deprecated in v1.1 and will be removed in version 1.3. Use `loss='log_loss'` which is equivalent.
  warnings.warn(
C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:163: FutureWarning: The loss 'log' was deprecated in v1.1 and will

GridSearchCV(cv=5, estimator=SGDClassifier(),
             param_grid={'alpha': [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0,
                                   1000.0],
                         'loss': ['log'], 'n_jobs': [-1], 'penalty': ['l2']},
             scoring='accuracy')

In [22]:
gs.best_params_

{'alpha': 0.0001, 'loss': 'log', 'n_jobs': -1, 'penalty': 'l2'}

In [23]:
# best sgd classifier model 
best_sgd = SGDClassifier(alpha=0.0001,loss='log',n_jobs=-1,penalty='l2')
best_sgd.fit(X_train,y_train)
filename = 'best_sgd.sav'
pickle.dump(best_sgd, open(filename, 'wb'))

C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:163: FutureWarning: The loss 'log' was deprecated in v1.1 and will be removed in version 1.3. Use `loss='log_loss'` which is equivalent.
  warnings.warn(


### accuracies of best model


In [24]:
y_train_pred = best_sgd.predict(X_train)
y_valid_pred = best_sgd.predict(X_valid)
y_test_pred  = best_sgd.predict(X_test)
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred)}")
print(f" The validation data accuracy for the best model is {accuracy_score(y_valid,y_valid_pred)}")
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred)}")
      

 The training data accuracy for the best model is 0.750119641758392
 The validation data accuracy for the best model is 0.7469064059615779
 The testing data accuracy for the best model is 0.7491796554552912


### confusion matrix for best model for all sets

In [25]:
# confusion matrix for training data
print(confusion_matrix(y_train,y_train_pred))

[[2492    0    0    0    0  126    0    0   66    0    0]
 [   2 1081  141  212   18   59    0    0   21 1029    0]
 [   0  194 1452  500  230  190    2    0    5  166    0]
 [   0   10   46 2489   14    0    4    0    0  125    0]
 [   0    6  227  656 1358   63    1  352   51    2    0]
 [ 543    7   22    0    9 1672    0    4  351    0    0]
 [   0    0    0    8    0    0 2678    0    0    0    0]
 [  40    1   28   80  321  163    0 1925   97    1    0]
 [  65    2   34   11   78  476    0    8 2023    2    0]
 [   0  248    9  181    2    1    0    0    0 2176    0]
 [   0    0    0    0    0    0    0    0    0    0 2598]]


In [26]:
# confusion matrix for training data
print(confusion_matrix(y_valid,y_valid_pred))

[[1228    0    0    0    0   67    0    1   36    0    0]
 [   0  512   92  128    8   29    0    0   11  609    0]
 [   0   96  672  254   97   93    2    0    4   72    0]
 [   0    1   17 1236    6    0    3    0    0   73    0]
 [   0    5  121  286  676   37    1  154   20    2    0]
 [ 273    3    6    0    5  881    0    3  169    0    0]
 [   0    0    0    4    0    0 1301    0    0    0    0]
 [  13    0   19   37  153   94    1  955   47    0    0]
 [  43    5   12    3   25  237    0    4  996    0    0]
 [   0  138    3   75    2    2    0    0    0 1122    1]
 [   0    0    0    0    0    0    0    0    0    0 1346]]


In [27]:
# confusion matrix for testing data
print(confusion_matrix(y_test,y_test_pred))

[[1205    0    0    0    0   61    0    2   35    0    0]
 [   0  531   76  119    6   40    0    0   19  575    1]
 [   0   99  714  231   85   86    2    0    1   72    0]
 [   0    1   16 1210    7    0    4    0    0   57    0]
 [   1    3  106  294  671   31    0  181   13    1    0]
 [ 303    5    7    0    9  859    0    3  185    0    0]
 [   0    0    0    4    0    0 1324    0    0    0    0]
 [  25    0   17   33  154   92    2  975   46    0    0]
 [  33    4   23    6   41  223    0    1  964    0    0]
 [   0  139    2   82    4    1    0    0    0 1131    0]
 [   0    0    0    0    0    0    0    0    0    0 1375]]


### classification report for the models 

In [28]:
# classification report for the training data
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           1       0.79      0.93      0.86      2684
           2       0.70      0.42      0.53      2563
           3       0.74      0.53      0.62      2739
           4       0.60      0.93      0.73      2688
           5       0.67      0.50      0.57      2716
           6       0.61      0.64      0.62      2608
           7       1.00      1.00      1.00      2686
           8       0.84      0.72      0.78      2656
           9       0.77      0.75      0.76      2699
          10       0.62      0.83      0.71      2617
          11       1.00      1.00      1.00      2598

    accuracy                           0.75     29254
   macro avg       0.76      0.75      0.74     29254
weighted avg       0.76      0.75      0.74     29254



In [29]:
# classification report for the validation data
print(classification_report(y_valid,y_valid_pred))

              precision    recall  f1-score   support

           1       0.79      0.92      0.85      1332
           2       0.67      0.37      0.48      1389
           3       0.71      0.52      0.60      1290
           4       0.61      0.93      0.74      1336
           5       0.70      0.52      0.59      1302
           6       0.61      0.66      0.63      1340
           7       0.99      1.00      1.00      1305
           8       0.85      0.72      0.78      1319
           9       0.78      0.75      0.76      1325
          10       0.60      0.84      0.70      1343
          11       1.00      1.00      1.00      1346

    accuracy                           0.75     14627
   macro avg       0.76      0.75      0.74     14627
weighted avg       0.76      0.75      0.74     14627



In [30]:
# classification report for the testing data
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           1       0.77      0.92      0.84      1303
           2       0.68      0.39      0.49      1367
           3       0.74      0.55      0.63      1290
           4       0.61      0.93      0.74      1295
           5       0.69      0.52      0.59      1301
           6       0.62      0.63      0.62      1371
           7       0.99      1.00      1.00      1328
           8       0.84      0.73      0.78      1344
           9       0.76      0.74      0.75      1295
          10       0.62      0.83      0.71      1359
          11       1.00      1.00      1.00      1375

    accuracy                           0.75     14628
   macro avg       0.76      0.75      0.74     14628
weighted avg       0.76      0.75      0.74     14628



### Roc auc score for the models 

In [33]:
y_train_prob = best_sgd.predict_proba(X_train)
y_valid_prob = best_sgd.predict_proba(X_valid)
y_test_prob  = best_sgd.predict_proba(X_test)


In [34]:
print(f" The roc_auc score for the training data is {roc_auc_score(y_train,y_train_prob,average='weighted',multi_class='ovr')}")
print(f" The roc_auc score for the validation data is {roc_auc_score(y_valid,y_valid_prob,average='weighted',multi_class='ovr')}")
print(f" The roc_auc score for the testing data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The roc_auc score for the training data is 0.9691666553922633
 The roc_auc score for the validation data is 0.9693981894782019
 The roc_auc score for the testing data is 0.9692134384375816


### Recall  scores for models 

In [35]:
# recall score for training data
print(f" The recall score for the training data is {recall_score(y_train,y_train_pred,average= 'macro')}")
# recall score for validation data
print(f" The recall score for the validation data is {recall_score(y_valid,y_valid_pred,average= 'macro')}")
# recall score for test data
print(f" The recall score for the testing data is {recall_score(y_valid,y_valid_pred,average= 'macro')}")

 The recall score for the training data is 0.7500224879845168
 The recall score for the validation data is 0.747398696124673
 The recall score for the testing data is 0.747398696124673


### f1-score for the models 

In [36]:
# F-1 score for training data
print(f" The f-1 score for the training data is {f1_score(y_train,y_train_pred,average= 'weighted')}")
# F-1 score for validation data
print(f" The f-1 score for the validation data is {f1_score(y_valid,y_valid_pred,average= 'weighted')}")
# F-1 score for test data
print(f" The f-1 score for the testing data is {f1_score(y_valid,y_valid_pred,average= 'weighted')}")

 The f-1 score for the training data is 0.7431666740126543
 The f-1 score for the validation data is 0.7386673858806371
 The f-1 score for the testing data is 0.7386673858806371


# using Logistic Regression

In [80]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(X_train,y_train)
y_train_pred = log.predict(X_train)
y_valid_pred = log.predict(X_valid)
y_test_pred = log.predict(X_test)
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred)}")
print(f" The validation data accuracy for the best model is {accuracy_score(y_valid,y_valid_pred)}")
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred)}")
      

 The training data accuracy for the best model is 0.8962535037943529
 The validation data accuracy for the best model is 0.8949203527722704
 The testing data accuracy for the best model is 0.894927536231884


C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [81]:
from sklearn.linear_model import LogisticRegression
# logistic regression hyper parameter validation
parameters = {
    'penalty' : ['l1','l2'], 
    'solver'  : ['newton-cg', 'lbfgs', 'liblinear'],
}

logreg = LogisticRegression()
gs = GridSearchCV(logreg,                    # model
                   param_grid = parameters,   # hyperparameters
                   scoring='accuracy',        # metric for scoring
                   cv=5)                  # number of folds
gs.fit(X_valid,y_valid)                  

C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'penalty': ['l1', 'l2'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear']},
             scoring='accuracy')

In [82]:
gs.best_params_

{'penalty': 'l2', 'solver': 'newton-cg'}

In [93]:
best_log = LogisticRegression(penalty= 'l2',solver='newton-cg')
best_log.fit(X_train,y_train)
filename = 'best_log.sav'
pickle.dump(best_log, open(filename, 'wb'))

### Accuracies of the models 

In [84]:
y_train_pred = best_log.predict(X_train)
y_valid_pred = best_log.predict(X_valid)
y_test_pred = best_log.predict(X_test)
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred)}")
print(f" The validation data accuracy for the best model is {accuracy_score(y_valid,y_valid_pred)}")
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred)}")
      

 The training data accuracy for the best model is 0.9095850140151774
 The validation data accuracy for the best model is 0.9085253298694196
 The testing data accuracy for the best model is 0.9079846869018321


### Recall score of the models 

In [85]:
# recall score for training data
print(f" The recall score for the training data is {recall_score(y_train,y_train_pred,average= 'macro')}")
# recall score for validation data
print(f" The recall score for the validation data is {recall_score(y_valid,y_valid_pred,average= 'macro')}")
# recall score for test data
print(f" The recall score for the testing data is {recall_score(y_valid,y_valid_pred,average= 'macro')}")

 The recall score for the training data is 0.9095806868150568
 The recall score for the validation data is 0.9085545233344728
 The recall score for the testing data is 0.9085545233344728


### f1 score of the models 

In [86]:
# F-1 score for training data
print(f" The f-1 score for the training data is {f1_score(y_train,y_train_pred,average= 'weighted')}")
# F-1 score for validation data
print(f" The f-1 score for the validation data is {f1_score(y_valid,y_valid_pred,average= 'weighted')}")
# F-1 score for test data
print(f" The f-1 score for the testing data is {f1_score(y_valid,y_valid_pred,average= 'weighted')}")

 The f-1 score for the training data is 0.9090777181014986
 The f-1 score for the validation data is 0.9079970743606399
 The f-1 score for the testing data is 0.9079970743606399


### Roc_Auc_score of the models 

In [88]:
y_train_prob = best_log.predict_proba(X_train)
y_valid_prob = best_log.predict_proba(X_valid)
y_test_prob = best_log.predict_proba(X_test)
print(f" The roc_auc score for the training data is {roc_auc_score(y_train,y_train_prob,average='weighted',multi_class='ovr')}")
print(f" The roc_auc score for the validation data is {roc_auc_score(y_valid,y_valid_prob,average='weighted',multi_class='ovr')}")
print(f" The roc_auc score for the testing data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The roc_auc score for the training data is 0.9947233950917425
 The roc_auc score for the validation data is 0.9945940875405269
 The roc_auc score for the testing data is 0.9944914153014618


In [89]:
#confusion matrix of the training data
print(confusion_matrix(y_train,y_train_pred))

[[2578    0    0    0    0   96    0    0   10    0    0]
 [   1 2255    0    0    0    0    0    0    9  298    0]
 [   0    0 2557   60  121    1    0    0    0    0    0]
 [   0    0  100 2551   32    0    4    1    0    0    0]
 [   0    0  129   94 2120    0    0  372    0    1    0]
 [ 171    1    2    0    0 2169    0    2  263    0    0]
 [   0    0    0    2    0    0 2684    0    0    0    0]
 [   1    0   10   13  193    0    0 2438    0    1    0]
 [  21   13    8    0    0  305    0    1 2345    6    0]
 [   0  300    0    1    0    0    0    0    2 2314    0]
 [   0    0    0    0    0    0    0    0    0    0 2598]]


In [90]:
# confusion matrix for the validation data
print(confusion_matrix(y_valid,y_valid_pred))

[[1271    0    0    0    0   51    0    0   10    0    0]
 [   0 1241    1    0    0    0    0    0    2  145    0]
 [   0    0 1217   30   43    0    0    0    0    0    0]
 [   0    0   51 1266   15    0    4    0    0    0    0]
 [   0    0   72   47 1018    0    0  165    0    0    0]
 [  91    0    1    0    2 1109    0    2  135    0    0]
 [   0    0    0    2    0    0 1303    0    0    0    0]
 [   0    0    9    5   87    1    0 1217    0    0    0]
 [   4    4    6    0    0  175    0    0 1135    1    0]
 [   0  177    0    0    0    0    0    0    0 1166    0]
 [   0    0    0    0    0    0    0    0    0    0 1346]]


In [91]:
# confusion matrix for the test data
print(confusion_matrix(y_test,y_test_pred))

[[1254    0    0    0    0   39    0    0   10    0    0]
 [   0 1196    0    1    0    0    0    0    6  163    1]
 [   0    0 1201   27   60    0    0    0    2    0    0]
 [   0    0   42 1236   14    0    3    0    0    0    0]
 [   0    0   50   47 1017    0    0  187    0    0    0]
 [  96    0    0    0    1 1126    0    1  147    0    0]
 [   0    0    0    0    0    0 1328    0    0    0    0]
 [   0    0    3    5  101    0    1 1234    0    0    0]
 [   4    3    8    2    0  137    0    1 1137    3    0]
 [   0  180    0    0    0    0    0    0    1 1178    0]
 [   0    0    0    0    0    0    0    0    0    0 1375]]


In [92]:
# classification report for training data
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           1       0.93      0.96      0.95      2684
           2       0.88      0.88      0.88      2563
           3       0.91      0.93      0.92      2739
           4       0.94      0.95      0.94      2688
           5       0.86      0.78      0.82      2716
           6       0.84      0.83      0.84      2608
           7       1.00      1.00      1.00      2686
           8       0.87      0.92      0.89      2656
           9       0.89      0.87      0.88      2699
          10       0.88      0.88      0.88      2617
          11       1.00      1.00      1.00      2598

    accuracy                           0.91     29254
   macro avg       0.91      0.91      0.91     29254
weighted avg       0.91      0.91      0.91     29254

