In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pickle

In [2]:
data = pd.read_csv('Group_9_data_cleaned.csv')
data.head(3)
# removing a redundant column
df = data.drop(['Unnamed: 0'],axis=1)
df.head()

current_1     current_2  current_3  current_4     current_5  current_6  \
0 -3.014600e-07  8.260300e-06  -0.000012  -0.000002 -1.438600e-06  -0.000021   
1  2.913200e-06 -5.247700e-06   0.000003  -0.000006  2.778900e-06  -0.000004   
2 -2.951700e-06 -3.184000e-06  -0.000016  -0.000001 -1.575300e-06   0.000017   
3 -1.322600e-06  8.820100e-06  -0.000016  -0.000005 -7.282900e-07   0.000004   
4 -6.836600e-08  5.666300e-07  -0.000026  -0.000006 -7.940600e-07   0.000013   

   current_7  current_8  current_9  current_10  ...  current_40  current_41  \
0   0.031718   0.031710   0.031721   -0.032963  ...    -0.63308      2.9646   
1   0.030804   0.030810   0.030806   -0.033520  ...    -0.59314      7.6252   
2   0.032877   0.032880   0.032896   -0.029834  ...    -0.63252      2.7784   
3   0.029410   0.029401   0.029417   -0.030156  ...    -0.62289      6.5534   
4   0.030119   0.030119   0.030145   -0.031393  ...    -0.63010      4.5155   

   current_42  current_43  current_44  current_45  current_46  current_47  \
0      8.1198     -1.4961     -1.4961     -1.4961     -1.4996     -1.4996   
1      6.1690     -1.4967     -1.4967     -1.4967     -1.5005     -1.5005   
2      5.3017     -1.4983     -1.4983     -1.4982     -1.4985     -1.4985   
3      6.2606     -1.4963     -1.4963     -1.4963     -1.4975     -1.4975   
4      9.5231     -1.4958     -1.4958     -1.4958     -1.4959     -1.4959   

   current_48  output  
0     -1.4996       1  
1     -1.5005       1  
2     -1.4985       1  
3     -1.4976       1  
4     -1.4959       1  

[5 rows x 49 columns]

In [3]:
#shape of the data 
# The data has 58509 rows 
# The data has 49 features 
df.shape

(58509, 49)

In [4]:
# statistics of the data 
df.describe()

current_1     current_2     current_3     current_4     current_5  \
count  58509.000000  5.850900e+04  5.850900e+04  5.850900e+04  5.850900e+04   
mean      -0.000003  1.756436e-06  1.111802e-06 -9.722586e-07  1.775487e-06   
std        0.000008  3.199783e-05  1.520782e-04  7.956279e-06  3.234750e-05   
min       -0.000021 -6.427550e-05 -2.937900e-04 -1.887580e-05 -6.547550e-05   
25%       -0.000007 -1.444400e-05 -7.239600e-05 -5.417500e-06 -1.475300e-05   
50%       -0.000003  8.804600e-07  5.137700e-07 -1.059100e-06  7.540200e-07   
75%        0.000002  1.877700e-05  7.520000e-05  3.554700e-06  1.906200e-05   
max        0.000015  6.860850e-05  2.965940e-04  1.701300e-05  6.978450e-05   

          current_6     current_7     current_8     current_9    current_10  \
count  5.850900e+04  58509.000000  58509.000000  58509.000000  58509.000000   
mean  -7.457535e-07      0.002854      0.002849      0.002849     -0.006349   
std    1.490893e-04      0.033692      0.033700      0.033701      0.050735   
min   -2.915565e-04     -0.086972     -0.087041     -0.086978     -0.111281   
25%   -7.379100e-05     -0.019927     -0.019951     -0.019925     -0.032144   
50%   -1.659300e-07      0.013226      0.013230      0.013247     -0.015566   
75%    7.138600e-05      0.024770      0.024776      0.024777      0.020614   
max    2.891515e-04      0.069125      0.069130      0.069131      0.099751   

       ...    current_40    current_41    current_42    current_43  \
count  ...  58509.000000  58509.000000  58509.000000  58509.000000   
mean   ...     -0.650427      5.730645      7.702923     -1.500891   
std    ...      0.100670      5.781169      4.347205      0.003629   
min    ...     -0.902350     -0.596830      0.320660     -1.510950   
25%    ...     -0.715470      1.450300      4.436300     -1.503300   
50%    ...     -0.661710      3.301300      6.479100     -1.500300   
75%    ...     -0.573980      8.288500      9.857500     -1.498200   
max    ...     -0.361745     18.545800     17.989300     -1.490550   

         current_44    current_45    current_46    current_47    current_48  \
count  58509.000000  58509.000000  58509.000000  58509.000000  58509.000000   
mean      -1.500915     -1.500809     -1.497787     -1.497814     -1.497710   
std        0.003640      0.003600      0.003002      0.002984      0.002988   
min       -1.511200     -1.510700     -1.504700     -1.504550     -1.504450   
25%       -1.503400     -1.503200     -1.499600     -1.499600     -1.499500   
50%       -1.500300     -1.500300     -1.498100     -1.498100     -1.498000   
75%       -1.498200     -1.498200     -1.496200     -1.496300     -1.496200   
max       -1.490400     -1.490700     -1.491100     -1.491350     -1.491250   

             output  
count  58509.000000  
mean       6.000000  
std        3.162305  
min        1.000000  
25%        3.000000  
50%        6.000000  
75%        9.000000  
max       11.000000  

[8 rows x 49 columns]

In [5]:
# There are 11 different classes in the output data 
# which are from 1 to 11 classes 
df['output'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [6]:
# Checking for the number of each output class labels 
# It is a blanced multi class dataset with each class is having equal number of output labels 
df['output'].value_counts()


1     5319
2     5319
3     5319
4     5319
5     5319
6     5319
7     5319
8     5319
9     5319
10    5319
11    5319
Name: output, dtype: int64

In [7]:
# Dividing input and output labels
X = df.drop(['output'],axis=1)
y = df['output']


In [8]:
# importing Min Max scalar for the data transformation
# Scaling is very important in the case of linear regression
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_X = scaler.fit_transform(X)
print(scaled_X)

[[0.5730026  0.54585804 0.47811763 ... 0.375      0.375      0.36742424]
 [0.66228185 0.44420547 0.50328617 ... 0.30882353 0.30681818 0.29924242]
 [0.49939872 0.45973556 0.47065977 ... 0.45588235 0.45833333 0.45075758]
 ...
 [0.41869175 0.62362286 0.32534757 ... 1.         1.         1.        ]
 [0.45803432 0.73932528 0.         ... 0.84558824 0.85984848 0.85984848]
 [0.33549635 0.87696412 0.62036912 ... 0.75       0.75378788 0.76893939]]


In [9]:
# dividing the dataset into train,test and validation sets
X_train, X_rem, y_train, y_rem  = train_test_split(scaled_X, y, train_size = 0.5, random_state = 100)
X_valid, X_test, y_valid, y_test = train_test_split(X_rem, y_rem, test_size = 0.5, random_state = 100)

In [10]:
# The shape of training dataset
print(f" The input training  data shape is {X_train.shape}")
print(f" The  output training data shape is {y_train.shape}")
print(f" The input validation  data shape is {X_valid.shape}")
print(f" The  output validation data shape is {y_valid.shape}")
# The shape of the test dataset 
print(f" The input testing  data shape is {X_valid.shape}")
print(f" The  output testing data shape is {y_valid.shape}")

 The input training  data shape is (29254, 48)
 The  output training data shape is (29254,)
 The input validation  data shape is (14627, 48)
 The  output validation data shape is (14627,)
 The input testing  data shape is (14627, 48)
 The  output testing data shape is (14627,)


## Ensemble models 

In [11]:
#importing models
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import RidgeClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.neural_network import MLPClassifier

In [12]:

m1 = RandomForestClassifier()
m2 = AdaBoostClassifier()
m3 = GradientBoostingClassifier()
m4 = BaggingClassifier()
m5 = RandomForestClassifier(n_estimators= 10, max_features= 'sqrt', max_depth= 3,bootstrap=True)
m6 = AdaBoostClassifier(n_estimators= 10)
m7 = DecisionTreeClassifier()
m8 = DecisionTreeClassifier(max_depth=5)
m9 = DecisionTreeClassifier(splitter='random', min_samples_split= 7, min_samples_leaf= 1, 
                                  max_depth= 2)
m10 = AdaBoostClassifier(n_estimators=40,random_state=0)
m11 = RandomForestClassifier(n_estimators= 100, max_features= 'sqrt', max_depth= 4,bootstrap=False)
m12 = AdaBoostClassifier(n_estimators = 50,random_state=0)
m13 = LogisticRegression()
m14 = KNeighborsClassifier(n_neighbors=8)
m15 = KNeighborsClassifier(n_neighbors=5)
m16 = svm.SVC(kernel ='linear',C=100,gamma=1,probability=True)
m17 = svm.SVC(C= 100, gamma= 0.1, kernel= 'rbf',probability=True)
m18 = RandomForestClassifier(n_estimators= 5, max_features= 'sqrt', max_depth= 4,bootstrap=False)
m19 = GaussianNB()
m20 = MLPClassifier()

In [19]:
# Ensemble Classifier

en_cls = VotingClassifier(estimators=[('r_1', m1),('ab_1', m2),('gb', m3),('bg', m4),('random_2',m5),('ada_2',m6),('decision_t_1',m7),('deci_t',m8),
    ('decisiontree',m9),('adaboost',m10),('randomforest',m11),('ada_classifier',m12),('lg',m13),('knn_1',m14),('Kneigh',m15),('svm_1',m16),('svm_classifier',m17),
                                     ('random_classifier',m18),('gb_2',m19),('rdg',m20)],voting="soft")
en_cls = en_cls.fit(X_train,y_train)

C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [20]:
from sklearn.metrics import confusion_matrix, classification_report, recall_score, accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

In [21]:
# accuracy for train and validation sets
y_train_pred = en_cls.predict(X_train)
y_valid_pred = en_cls.predict(X_valid)
y_test_pred  = en_cls.predict(X_test)
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred)}")
print(f" The validation data accuracy for the best model is {accuracy_score(y_valid,y_valid_pred)}")
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred)}")
      

 The training data accuracy for the best model is 0.99822246530389
 The validation data accuracy for the best model is 0.9901551924523142
 The testing data accuracy for the best model is 0.9907027618266339


In [22]:
# confusion matrix for the test data
print(confusion_matrix(y_test,y_test_pred))

[[1299    0    0    0    0    4    0    0    0    0    0]
 [   0 1345    0    0    0    0    0    0    0   21    1]
 [   0    0 1284    0    5    0    0    0    1    0    0]
 [   0    0    2 1292    1    0    0    0    0    0    0]
 [   0    0    3    2 1277    0    0   19    0    0    0]
 [   5    0    1    0    0 1363    0    0    2    0    0]
 [   0    0    0    0    0    0 1328    0    0    0    0]
 [   0    0    0    2    9    0    0 1333    0    0    0]
 [   0    1    0    0    0    6    0    1 1285    2    0]
 [   0   48    0    0    0    0    0    0    0 1311    0]
 [   0    0    0    0    0    0    0    0    0    0 1375]]


In [23]:
# classification report for test data
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00      1303
           2       0.96      0.98      0.97      1367
           3       1.00      1.00      1.00      1290
           4       1.00      1.00      1.00      1295
           5       0.99      0.98      0.98      1301
           6       0.99      0.99      0.99      1371
           7       1.00      1.00      1.00      1328
           8       0.99      0.99      0.99      1344
           9       1.00      0.99      0.99      1295
          10       0.98      0.96      0.97      1359
          11       1.00      1.00      1.00      1375

    accuracy                           0.99     14628
   macro avg       0.99      0.99      0.99     14628
weighted avg       0.99      0.99      0.99     14628



In [24]:
# roc auc score, f1 score and recall score for the model using test data
# F-1 score for test data
print(f" The f-1 score for the testing data is {f1_score(y_test,y_test_pred,average= 'weighted')}")
# recall score for test data
print(f" The recall score for the testing data is {recall_score(y_test,y_test_pred,average= 'macro')}")
y_test_prob = en_cls.predict_proba(X_test)
print(f" The roc_auc score for the testing data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The f-1 score for the testing data is 0.9907023409847315
 The recall score for the testing data is 0.9907599668650309
 The roc_auc score for the testing data is 0.9999098191200902


### comparing with the other models from part -2  for test data

In [26]:
import pickle

#Load the trained Best Linear Regression model
sgd=pickle.load(open('best_sgd.sav', 'rb'))
# load Logistic Regression model
log = pickle.load(open('best_log.sav','rb'))
#load the best knn model
knn = pickle.load(open('knn_class.sav', 'rb'))
#load Random fores model
rf = pickle.load(open('RF_class.sav', 'rb'))
#load Decision Trees model
dt = pickle.load(open('Tree_class.sav','rb'))


In [38]:
# Test results for stochastic gradient classifier
sgd.fit(X_train,y_train)
y_test_pred = sgd.predict(X_test)
y_test_proba = sgd.predict_proba(X_test)
y_train_pred = sgd.predict(X_train)
print(f" The train data accuracy sgd model is {accuracy_score(y_train,y_train_pred)}")
print(f" The test data accuracy sgd model is {accuracy_score(y_test,y_test_pred)}")
# F-1 score for test data
print(f" The f-1 score for the test data is {f1_score(y_test,y_test_pred,average= 'weighted')}")
# recall score for test data
print(f" The recall score for the test  data is {recall_score(y_test,y_test_pred,average= 'macro')}")
print(f" The roc_auc score for the test  data is {roc_auc_score(y_test,y_test_proba,average='weighted',multi_class='ovr')}")

C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:163: FutureWarning: The loss 'log' was deprecated in v1.1 and will be removed in version 1.3. Use `loss='log_loss'` which is equivalent.
  warnings.warn(


 The train data accuracy sgd model is 0.7110138784439735
 The test data accuracy sgd model is 0.717391304347826
 The f-1 score for the test data is 0.707233840421796
 The recall score for the test  data is 0.7134731912978303
 The roc_auc score for the test  data is 0.9678055964386405


In [39]:
# Test results for logistic regression
log.fit(X_train,y_train)
y_test_pred = log.predict(X_test)
y_test_prob = log.predict_proba(X_test)
y_train_pred = log.predict(X_train)
print(f" The train data accuracy logistic model is {accuracy_score(y_train,y_train_pred)}")
print(f" The test data accuracy logistic model is {accuracy_score(y_test,y_test_pred)}")
# F-1 score for test data
print(f" The f-1 score for the test data is {f1_score(y_test,y_test_pred,average= 'weighted')}")
# recall score for test data
print(f" The recall score for the test  data is {recall_score(y_test,y_test_pred,average= 'macro')}")
print(f" The roc_auc score for the test  data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The train data accuracy logistic model is 0.9095850140151774
 The test data accuracy logistic model is 0.9079846869018321
 The f-1 score for the test data is 0.9074211119324297
 The recall score for the test  data is 0.9080651377504487
 The roc_auc score for the test  data is 0.9944914153014618


In [40]:
# Test results for KNN classification
knn.fit(X_train,y_train)
y_test_pred = knn.predict(X_test)
y_test_prob = knn.predict_proba(X_test)
y_train_pred = knn.predict(X_train)
print(f" The train data accuracy knn model is {accuracy_score(y_train,y_train_pred)}")
print(f" The test data accuracy knn model is {accuracy_score(y_test,y_test_pred)}")
# F-1 score for test data
print(f" The f-1 score for the test data is {f1_score(y_test,y_test_pred,average= 'weighted')}")
# recall score for test data
print(f" The recall score for the test  data is {recall_score(y_test,y_test_pred,average= 'macro')}")
print(f" The roc_auc score for the test  data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The train data accuracy knn model is 1.0
 The test data accuracy knn model is 0.977167076838939
 The f-1 score for the test data is 0.9771679005724067
 The recall score for the test  data is 0.9773191105658197
 The roc_auc score for the test  data is 0.9994541676847498


In [41]:
# Test results for decision tree classification
dt.fit(X_train,y_train)
y_test_pred = dt.predict(X_test)
y_test_prob = dt.predict_proba(X_test)
y_train_pred = dt.predict(X_train)
print(f" The train data accuracy trees model is {accuracy_score(y_train,y_train_pred)}")
print(f" The test data accuracy decision tree model is {accuracy_score(y_test,y_test_pred)}")
# F-1 score for test data
print(f" The f-1 score for the test data is {f1_score(y_test,y_test_pred,average= 'weighted')}")
# recall score for test data
print(f" The recall score for the test  data is {recall_score(y_test,y_test_pred,average= 'macro')}")
print(f" The roc_auc score for the test  data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The train data accuracy trees model is 0.9800369180283038
 The test data accuracy decision tree model is 0.9695105277549905
 The f-1 score for the test data is 0.9696162578144502
 The recall score for the test  data is 0.9693421187900643
 The roc_auc score for the test  data is 0.9947688638135779


In [42]:
# Test results for random forest classification
rf.fit(X_train,y_train)
y_test_pred = rf.predict(X_test)
y_test_prob = rf.predict_proba(X_test)
y_train_pred = rf.predict(X_train)
print(f" The train data accuracy random forest model is {accuracy_score(y_train,y_train_pred)}")
print(f" The test data accuracy random forest model is {accuracy_score(y_test,y_test_pred)}")
# F-1 score for test data
print(f" The f-1 score for the test data is {f1_score(y_test,y_test_pred,average= 'weighted')}")
# recall score for test data
print(f" The recall score for the test  data is {recall_score(y_test,y_test_pred,average= 'macro')}")
print(f" The roc_auc score for the test  data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The train data accuracy random forest model is 0.99347097832775
 The test data accuracy random forest model is 0.9902242275088871
 The f-1 score for the test data is 0.9902190906089697
 The recall score for the test  data is 0.9901383172987909
 The roc_auc score for the test  data is 0.9999107455760874


### comparing models from part-3  

In [32]:
#Load the best svm linear model
svm_linear=pickle.load(open('svm_linear.sav', 'rb'))
# load the best non linear svm model
svm_nonlinear = pickle.load(open('svm_nonlinear.sav','rb'))
#load the best deep learning model
mlp = pickle.load(open('mlp.sav', 'rb'))



In [43]:
# Test results for svm linear classification
svm_linear.fit(X_train,y_train)
y_test_pred = svm_linear.predict(X_test)
y_test_prob = svm_linear.predict_proba(X_test)
y_train_pred = svm_linear.predict(X_train)
print(f" The train data accuracy svm linear model is {accuracy_score(y_train,y_train_pred)}")
print(f" The test data accuracy svm linear model is {accuracy_score(y_test,y_test_pred)}")
# F-1 score for test data
print(f" The f-1 score for the test data is {f1_score(y_test,y_test_pred,average= 'weighted')}")
# recall score for test data
print(f" The recall score for the test  data is {recall_score(y_test,y_test_pred,average= 'macro')}")
print(f" The roc_auc score for the test  data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The train data accuracy svm linear model is 0.9402474875230737
 The test data accuracy svm linear model is 0.9365600218758545
 The f-1 score for the test data is 0.9363181793454444
 The recall score for the test  data is 0.9367212302821362
 The roc_auc score for the test  data is 0.9967427231962683


In [44]:
# Test results for svm Non linear classification
svm_nonlinear.fit(X_train,y_train)
y_test_pred = svm_nonlinear.predict(X_test)
y_test_prob = svm_nonlinear.predict_proba(X_test)
y_train_pred = svm_nonlinear.predict(X_train)
print(f" The train data accuracy svm non linear model is {accuracy_score(y_train,y_train_pred)}")
print(f" The test data accuracy svm non linear model is {accuracy_score(y_test,y_test_pred)}")
# F-1 score for test data
print(f" The f-1 score for the test data is {f1_score(y_test,y_test_pred,average= 'weighted')}")
# recall score for test data
print(f" The recall score for the test  data is {recall_score(y_test,y_test_pred,average= 'macro')}")
print(f" The roc_auc score for the test  data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The train data accuracy svm non linear model is 0.9960347302932933
 The test data accuracy svm non linear model is 0.9849603500136724
 The f-1 score for the test data is 0.9849551502008304
 The recall score for the test  data is 0.9851186874234373
 The roc_auc score for the test  data is 0.9997320141256982


In [45]:
# Test results for deep learning mlp classification
mlp.fit(X_train,y_train)
y_test_pred = mlp.predict(X_test)
y_test_prob = mlp.predict_proba(X_test)
y_train_pred = mlp.predict(X_train)
print(f" The train data accuracy mlp model is {accuracy_score(y_train,y_train_pred)}")
print(f" The test data accuracy mlp model is {accuracy_score(y_test,y_test_pred)}")
# F-1 score for test data
print(f" The f-1 score for the test data is {f1_score(y_test,y_test_pred,average= 'weighted')}")
# recall score for test data
print(f" The recall score for the test  data is {recall_score(y_test,y_test_pred,average= 'macro')}")
print(f" The roc_auc score for the test  data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


 The train data accuracy mlp model is 0.9994530662473508
 The test data accuracy mlp model is 0.9928903472791906
 The f-1 score for the test data is 0.992893330008273
 The recall score for the test  data is 0.9929074037979327
 The roc_auc score for the test  data is 0.999886270966743


In [ ]:
## By the comparison of all these models with the ensemble model , all the remaining models having much difference between-
# the training and testing accuracy , while ensemble model has little difference between the training and testing accuracy.
# The ensemble model has lower variance compared to other models.
# The ensemble model has slightly higher bias compare with deep learning and random forest models.