In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pickle

In [2]:
data = pd.read_csv('Group_9_data_cleaned.csv')
data.head(3)
# removing a redundant column
df = data.drop(['Unnamed: 0'],axis=1)
df.head()

current_1     current_2  current_3  current_4     current_5  current_6  \
0 -3.014600e-07  8.260300e-06  -0.000012  -0.000002 -1.438600e-06  -0.000021   
1  2.913200e-06 -5.247700e-06   0.000003  -0.000006  2.778900e-06  -0.000004   
2 -2.951700e-06 -3.184000e-06  -0.000016  -0.000001 -1.575300e-06   0.000017   
3 -1.322600e-06  8.820100e-06  -0.000016  -0.000005 -7.282900e-07   0.000004   
4 -6.836600e-08  5.666300e-07  -0.000026  -0.000006 -7.940600e-07   0.000013   

   current_7  current_8  current_9  current_10  ...  current_40  current_41  \
0   0.031718   0.031710   0.031721   -0.032963  ...    -0.63308      2.9646   
1   0.030804   0.030810   0.030806   -0.033520  ...    -0.59314      7.6252   
2   0.032877   0.032880   0.032896   -0.029834  ...    -0.63252      2.7784   
3   0.029410   0.029401   0.029417   -0.030156  ...    -0.62289      6.5534   
4   0.030119   0.030119   0.030145   -0.031393  ...    -0.63010      4.5155   

   current_42  current_43  current_44  current_45  current_46  current_47  \
0      8.1198     -1.4961     -1.4961     -1.4961     -1.4996     -1.4996   
1      6.1690     -1.4967     -1.4967     -1.4967     -1.5005     -1.5005   
2      5.3017     -1.4983     -1.4983     -1.4982     -1.4985     -1.4985   
3      6.2606     -1.4963     -1.4963     -1.4963     -1.4975     -1.4975   
4      9.5231     -1.4958     -1.4958     -1.4958     -1.4959     -1.4959   

   current_48  output  
0     -1.4996       1  
1     -1.5005       1  
2     -1.4985       1  
3     -1.4976       1  
4     -1.4959       1  

[5 rows x 49 columns]

In [3]:
#shape of the data 
# The data has 58509 rows 
# The data has 49 features 
df.shape

(58509, 49)

In [4]:
# statistics of the data 
df.describe()

current_1     current_2     current_3     current_4     current_5  \
count  58509.000000  5.850900e+04  5.850900e+04  5.850900e+04  5.850900e+04   
mean      -0.000003  1.756436e-06  1.111802e-06 -9.722586e-07  1.775487e-06   
std        0.000008  3.199783e-05  1.520782e-04  7.956279e-06  3.234750e-05   
min       -0.000021 -6.427550e-05 -2.937900e-04 -1.887580e-05 -6.547550e-05   
25%       -0.000007 -1.444400e-05 -7.239600e-05 -5.417500e-06 -1.475300e-05   
50%       -0.000003  8.804600e-07  5.137700e-07 -1.059100e-06  7.540200e-07   
75%        0.000002  1.877700e-05  7.520000e-05  3.554700e-06  1.906200e-05   
max        0.000015  6.860850e-05  2.965940e-04  1.701300e-05  6.978450e-05   

          current_6     current_7     current_8     current_9    current_10  \
count  5.850900e+04  58509.000000  58509.000000  58509.000000  58509.000000   
mean  -7.457535e-07      0.002854      0.002849      0.002849     -0.006349   
std    1.490893e-04      0.033692      0.033700      0.033701      0.050735   
min   -2.915565e-04     -0.086972     -0.087041     -0.086978     -0.111281   
25%   -7.379100e-05     -0.019927     -0.019951     -0.019925     -0.032144   
50%   -1.659300e-07      0.013226      0.013230      0.013247     -0.015566   
75%    7.138600e-05      0.024770      0.024776      0.024777      0.020614   
max    2.891515e-04      0.069125      0.069130      0.069131      0.099751   

       ...    current_40    current_41    current_42    current_43  \
count  ...  58509.000000  58509.000000  58509.000000  58509.000000   
mean   ...     -0.650427      5.730645      7.702923     -1.500891   
std    ...      0.100670      5.781169      4.347205      0.003629   
min    ...     -0.902350     -0.596830      0.320660     -1.510950   
25%    ...     -0.715470      1.450300      4.436300     -1.503300   
50%    ...     -0.661710      3.301300      6.479100     -1.500300   
75%    ...     -0.573980      8.288500      9.857500     -1.498200   
max    ...     -0.361745     18.545800     17.989300     -1.490550   

         current_44    current_45    current_46    current_47    current_48  \
count  58509.000000  58509.000000  58509.000000  58509.000000  58509.000000   
mean      -1.500915     -1.500809     -1.497787     -1.497814     -1.497710   
std        0.003640      0.003600      0.003002      0.002984      0.002988   
min       -1.511200     -1.510700     -1.504700     -1.504550     -1.504450   
25%       -1.503400     -1.503200     -1.499600     -1.499600     -1.499500   
50%       -1.500300     -1.500300     -1.498100     -1.498100     -1.498000   
75%       -1.498200     -1.498200     -1.496200     -1.496300     -1.496200   
max       -1.490400     -1.490700     -1.491100     -1.491350     -1.491250   

             output  
count  58509.000000  
mean       6.000000  
std        3.162305  
min        1.000000  
25%        3.000000  
50%        6.000000  
75%        9.000000  
max       11.000000  

[8 rows x 49 columns]

In [5]:
# There are 11 different classes in the output data 
# which are from 1 to 11 classes 
df['output'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [6]:
# Checking for the number of each output class labels 
# It is a blanced multi class dataset with each class is having equal number of output labels 
df['output'].value_counts()


1     5319
2     5319
3     5319
4     5319
5     5319
6     5319
7     5319
8     5319
9     5319
10    5319
11    5319
Name: output, dtype: int64

## classification with svm Linear kernel  

In [7]:
# Dividing input and output labels
X = df.drop(['output'],axis=1)
y = df['output']


In [8]:
# importing Min Max scalar for the data transformation
# Scaling is very important in the case of linear regression
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_X = scaler.fit_transform(X)
print(scaled_X)

[[0.5730026  0.54585804 0.47811763 ... 0.375      0.375      0.36742424]
 [0.66228185 0.44420547 0.50328617 ... 0.30882353 0.30681818 0.29924242]
 [0.49939872 0.45973556 0.47065977 ... 0.45588235 0.45833333 0.45075758]
 ...
 [0.41869175 0.62362286 0.32534757 ... 1.         1.         1.        ]
 [0.45803432 0.73932528 0.         ... 0.84558824 0.85984848 0.85984848]
 [0.33549635 0.87696412 0.62036912 ... 0.75       0.75378788 0.76893939]]


In [9]:
# dividing the dataset into train,test and validation sets
X_train, X_rem, y_train, y_rem  = train_test_split(scaled_X, y, train_size = 0.5, random_state = 100)
X_valid, X_test, y_valid, y_test = train_test_split(X_rem, y_rem, test_size = 0.5, random_state = 100)

In [10]:
# The shape of training dataset
print(f" The input training  data shape is {X_train.shape}")
print(f" The  output training data shape is {y_train.shape}")
print(f" The input validation  data shape is {X_valid.shape}")
print(f" The  output validation data shape is {y_valid.shape}")
# The shape of the test dataset 
print(f" The input testing  data shape is {X_valid.shape}")
print(f" The  output testing data shape is {y_valid.shape}")

 The input training  data shape is (29254, 48)
 The  output training data shape is (29254,)
 The input validation  data shape is (14627, 48)
 The  output validation data shape is (14627,)
 The input testing  data shape is (14627, 48)
 The  output testing data shape is (14627,)


In [12]:
from sklearn.metrics import confusion_matrix, classification_report, recall_score, accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn import svm

In [13]:
# importing a random model
from sklearn import svm
svc = svm.SVC(kernel ='linear')
svc.fit(X_train,y_train)

SVC(kernel='linear')

In [13]:
y_train_pred = svc.predict(X_train)
y_valid_pred = svc.predict(X_valid)
y_test_pred  = svc.predict(X_test)

#### accuracies of the random model 

In [14]:
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred)}")
print(f" The validation data accuracy for the best model is {accuracy_score(y_valid,y_valid_pred)}")
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred)}")
      

 The training data accuracy for the best model is 0.9311205305257401
 The validation data accuracy for the best model is 0.929035345593765
 The testing data accuracy for the best model is 0.9284249384741592


## Hyper parameter validation  using grid search

In [15]:
from sklearn.model_selection import cross_val_score, GridSearchCV, RandomizedSearchCV

In [17]:
svc = svm.SVC(kernel ='linear')
param_grid = {'C': [0.1, 1, 10, 100], 
              'gamma': [1, 0.1, 0.01, 0.001],
              'kernel': ['linear']}
grid = GridSearchCV(svc, param_grid, refit = True, verbose = 3)
grid.fit(X_valid,y_valid)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.895 total time=   5.0s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.883 total time=   5.2s
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.883 total time=   4.7s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.884 total time=   4.3s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.881 total time=   4.3s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.895 total time=   4.2s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.883 total time=   4.3s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.883 total time=   4.0s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.884 total time=   4.3s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.881 total time=   4.0s
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.895 total time=   3.9s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear;

GridSearchCV(estimator=SVC(kernel='linear'),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001],
                         'kernel': ['linear']},
             verbose=3)

In [18]:
grid.best_params_

{'C': 100, 'gamma': 1, 'kernel': 'linear'}

In [13]:
# best svm linear model
best_svc = svm.SVC(kernel ='linear',C=100,gamma=1,probability=True)
best_svc.fit(X_train,y_train)
file_name = 'svm_linear.sav'
pickle.dump(best_svc,open(file_name,'wb'))

### accuracies of the best model 

In [14]:
y_train_pred = best_svc.predict(X_train)
y_valid_pred = best_svc.predict(X_valid)
y_test_pred  = best_svc.predict(X_test)
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred)}")
print(f" The validation data accuracy for the best model is {accuracy_score(y_valid,y_valid_pred)}")
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred)}")
      

 The training data accuracy for the best model is 0.9402474875230737
 The validation data accuracy for the best model is 0.9345730498393382
 The testing data accuracy for the best model is 0.9365600218758545


### confusion matrix for train,test and validation datsets

In [15]:
### Training Data
print(confusion_matrix(y_train,y_train_pred))

[[2604    0    0    0    0   80    0    0    0    0    0]
 [   1 2355    0    0    0    0    0    0    4  203    0]
 [   0    0 2682    9   48    0    0    0    0    0    0]
 [   0    0   19 2656   13    0    0    0    0    0    0]
 [   0    0   46   27 2323    0    0  320    0    0    0]
 [  94    0    3    0    0 2329    0    0  182    0    0]
 [   0    0    0    0    0    0 2686    0    0    0    0]
 [   0    1    0   14  209    0    0 2432    0    0    0]
 [  26   11    0    0    0  184    0    0 2477    1    0]
 [   0  253    0    0    0    0    0    0    0 2364    0]
 [   0    0    0    0    0    0    0    0    0    0 2598]]


In [16]:
# confusion matrix for validation data
print(confusion_matrix(y_valid,y_valid_pred))

[[1285    0    0    0    0   46    0    0    1    0    0]
 [   0 1285    1    0    0    0    0    0    0  103    0]
 [   0    0 1264    3   21    0    0    0    2    0    0]
 [   0    0   12 1316    8    0    0    0    0    0    0]
 [   0    0   31   22 1105    0    0  144    0    0    0]
 [  61    0    4    0    0 1172    0    0  103    0    0]
 [   0    0    0    1    0    0 1304    0    0    0    0]
 [   0    0    0    6   95    0    0 1218    0    0    0]
 [   8    4    1    0    0  126    0    0 1185    1    0]
 [   0  153    0    0    0    0    0    0    0 1190    0]
 [   0    0    0    0    0    0    0    0    0    0 1346]]


In [17]:
# Confusion matrix for testing data svm linear kernel
print(confusion_matrix(y_test,y_test_pred))

[[1272    0    0    0    0   31    0    0    0    0    0]
 [   0 1265    0    0    0    0    0    0    1  100    1]
 [   0    0 1261    6   22    0    0    0    1    0    0]
 [   0    0    8 1277    9    0    1    0    0    0    0]
 [   0    0   22   24 1084    0    0  171    0    0    0]
 [  49    0    5    0    0 1211    0    0  106    0    0]
 [   0    0    0    0    0    0 1328    0    0    0    0]
 [   0    0    0    3  106    0    0 1235    0    0    0]
 [   8    5    1    0    1   92    0    0 1188    0    0]
 [   0  155    0    0    0    0    0    0    0 1204    0]
 [   0    0    0    0    0    0    0    0    0    0 1375]]


### classification report for the best model 

In [18]:
#Classification report for the training data
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           1       0.96      0.97      0.96      2684
           2       0.90      0.92      0.91      2563
           3       0.98      0.98      0.98      2739
           4       0.98      0.99      0.98      2688
           5       0.90      0.86      0.88      2716
           6       0.90      0.89      0.90      2608
           7       1.00      1.00      1.00      2686
           8       0.88      0.92      0.90      2656
           9       0.93      0.92      0.92      2699
          10       0.92      0.90      0.91      2617
          11       1.00      1.00      1.00      2598

    accuracy                           0.94     29254
   macro avg       0.94      0.94      0.94     29254
weighted avg       0.94      0.94      0.94     29254



In [19]:
# Classification report for the testing data
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           1       0.96      0.98      0.97      1303
           2       0.89      0.93      0.91      1367
           3       0.97      0.98      0.97      1290
           4       0.97      0.99      0.98      1295
           5       0.89      0.83      0.86      1301
           6       0.91      0.88      0.90      1371
           7       1.00      1.00      1.00      1328
           8       0.88      0.92      0.90      1344
           9       0.92      0.92      0.92      1295
          10       0.92      0.89      0.90      1359
          11       1.00      1.00      1.00      1375

    accuracy                           0.94     14628
   macro avg       0.94      0.94      0.94     14628
weighted avg       0.94      0.94      0.94     14628



In [20]:
# classification report for the validation data
print(classification_report(y_valid,y_valid_pred))

              precision    recall  f1-score   support

           1       0.95      0.96      0.96      1332
           2       0.89      0.93      0.91      1389
           3       0.96      0.98      0.97      1290
           4       0.98      0.99      0.98      1336
           5       0.90      0.85      0.87      1302
           6       0.87      0.87      0.87      1340
           7       1.00      1.00      1.00      1305
           8       0.89      0.92      0.91      1319
           9       0.92      0.89      0.91      1325
          10       0.92      0.89      0.90      1343
          11       1.00      1.00      1.00      1346

    accuracy                           0.93     14627
   macro avg       0.93      0.93      0.93     14627
weighted avg       0.93      0.93      0.93     14627



### ROC AUC score for the best model 

In [29]:

# roc auc score for training data
y_train_prob = best_svc.predict_proba(X_train)
print(f" The roc_auc score for the training data is {roc_auc_score(y_train,y_train_prob,average='weighted',multi_class='ovr')}")
# roc auc score for the validation data
y_valid_prob = best_svc.predict_proba(X_valid)
print(f" The roc_auc score for the validation data is {roc_auc_score(y_valid,y_valid_prob,average='weighted',multi_class='ovr')}")
# roc auc score for the testing data
y_test_prob = best_svc.predict_proba(X_test)
print(f" The roc_auc score for the testing data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The roc_auc score for the training data is 0.9973207305099111
 The roc_auc score for the validation data is 0.9969811902439999
 The roc_auc score for the testing data is 0.9967536766122579


### Recall score of the best model

In [30]:
# recall score for training data
print(f" The recall score for the training data is {recall_score(y_train,y_train_pred,average= 'macro')}")
# recall score for validation data
print(f" The recall score for the validation data is {recall_score(y_valid,y_valid_pred,average= 'macro')}")
# recall score for test data
print(f" The recall score for the testing data is {recall_score(y_test,y_test_pred,average= 'macro')}")

 The recall score for the training data is 0.9401255760050685
 The recall score for the validation data is 0.9346466286455641
 The recall score for the testing data is 0.9367212302821362


### F1 score of the best model 

In [31]:
# F-1 score for training data
print(f" The f-1 score for the training data is {f1_score(y_train,y_train_pred,average= 'weighted')}")
# F-1 score for validation data
print(f" The f-1 score for the validation data is {f1_score(y_valid,y_valid_pred,average= 'weighted')}")
# F-1 score for test data
print(f" The f-1 score for the testing data is {f1_score(y_test,y_test_pred,average= 'weighted')}")

 The f-1 score for the training data is 0.9401265071966416
 The f-1 score for the validation data is 0.9343657700706681
 The f-1 score for the testing data is 0.9363181793454444


# classification using Non Linear svm kernel

### Finding best model using Hyper parameter validation 

In [18]:
from sklearn.model_selection import cross_val_score, GridSearchCV, RandomizedSearchCV

In [33]:
svc = svm.SVC()
param_grid = {'C': [0.1, 1, 10, 100], 
              'gamma': [1, 0.1, 0.01, 0.001],
              'kernel': ['rbf','poly','sigmoid']}
grid = GridSearchCV(svc, param_grid, refit = True, verbose = 3)
grid.fit(X_valid,y_valid)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.775 total time=  13.1s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.766 total time=  13.9s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.774 total time=  16.7s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.780 total time=  15.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.786 total time=  13.7s
[CV 1/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.975 total time=   1.8s
[CV 2/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.975 total time=   1.8s
[CV 3/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.971 total time=   2.0s
[CV 4/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.975 total time=   2.0s
[CV 5/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.970 total time=   2.1s
[CV 1/5] END ....C=0.1, gamma=1, kernel=sigmoid;, score=0.095 total time=  16.7s
[CV 2/5] END ....C=0.1, gamma=1, kernel=sigmoid

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf', 'poly', 'sigmoid']},
             verbose=3)

In [34]:
grid.best_params_

{'C': 100, 'gamma': 0.1, 'kernel': 'rbf'}

In [14]:
# best svm non_linear model 
best_non_linear = svm.SVC(C= 100, gamma= 0.1, kernel= 'rbf',probability=True)
best_non_linear.fit(X_train,y_train)
file_name = 'svm_nonlinear.sav'
pickle.dump(best_non_linear,open(file_name,'wb'))

#### accuracies of the best model  

In [37]:
y_train_pred = best_non_linear.predict(X_train)
y_valid_pred = best_non_linear.predict(X_valid)
y_test_pred  = best_non_linear.predict(X_test)
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred)}")
print(f" The validation data accuracy for the best model is {accuracy_score(y_valid,y_valid_pred)}")
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred)}")
      

 The training data accuracy for the best model is 0.9960347302932933
 The validation data accuracy for the best model is 0.9860531893074451
 The testing data accuracy for the best model is 0.9849603500136724


### confusion matrix for the non linear svm best model 

In [38]:
### Training Data
print(confusion_matrix(y_train,y_train_pred))

[[2680    0    0    0    0    4    0    0    0    0    0]
 [   0 2539    0    0    0    0    0    0    0   24    0]
 [   0    0 2739    0    0    0    0    0    0    0    0]
 [   0    0    0 2688    0    0    0    0    0    0    0]
 [   0    0    1    0 2702    0    0   13    0    0    0]
 [   2    0    0    0    0 2604    0    0    2    0    0]
 [   0    0    0    0    0    0 2686    0    0    0    0]
 [   0    0    0    2   11    0    0 2643    0    0    0]
 [   0    0    0    0    0    3    0    0 2696    0    0]
 [   0   54    0    0    0    0    0    0    0 2563    0]
 [   0    0    0    0    0    0    0    0    0    0 2598]]


In [39]:
### validation Data
print(confusion_matrix(y_valid,y_valid_pred))

[[1321    0    0    0    0   11    0    0    0    0    0]
 [   0 1355    1    0    0    0    0    0    0   33    0]
 [   0    0 1288    0    2    0    0    0    0    0    0]
 [   0    0    0 1336    0    0    0    0    0    0    0]
 [   0    0    2    0 1275    0    0   25    0    0    0]
 [   6    0    0    0    0 1320    0    0   14    0    0]
 [   0    0    0    1    0    0 1304    0    0    0    0]
 [   0    0    0    5   22    0    0 1292    0    0    0]
 [   1    0    0    0    0    5    0    0 1318    1    0]
 [   0   75    0    0    0    0    0    0    0 1268    0]
 [   0    0    0    0    0    0    0    0    0    0 1346]]


In [40]:
### Test  Data for svm non linear model
print(confusion_matrix(y_test,y_test_pred))

[[1298    0    0    0    0    5    0    0    0    0    0]
 [   0 1323    0    0    0    0    0    0    0   43    1]
 [   0    0 1285    0    5    0    0    0    0    0    0]
 [   0    0    0 1294    0    0    1    0    0    0    0]
 [   0    0    3    0 1266    0    0   32    0    0    0]
 [  12    0    0    0    1 1346    0    0   12    0    0]
 [   0    0    0    0    0    0 1328    0    0    0    0]
 [   0    0    0    4   23    0    0 1317    0    0    0]
 [   2    0    0    0    0    8    0    0 1284    1    0]
 [   0   67    0    0    0    0    0    0    0 1292    0]
 [   0    0    0    0    0    0    0    0    0    0 1375]]


### classification report for the svm non linear best model 

In [41]:
#Classification report for the training data
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00      2684
           2       0.98      0.99      0.98      2563
           3       1.00      1.00      1.00      2739
           4       1.00      1.00      1.00      2688
           5       1.00      0.99      1.00      2716
           6       1.00      1.00      1.00      2608
           7       1.00      1.00      1.00      2686
           8       1.00      1.00      1.00      2656
           9       1.00      1.00      1.00      2699
          10       0.99      0.98      0.99      2617
          11       1.00      1.00      1.00      2598

    accuracy                           1.00     29254
   macro avg       1.00      1.00      1.00     29254
weighted avg       1.00      1.00      1.00     29254



In [42]:
#Classification report for the validation data
print(classification_report(y_valid,y_valid_pred))

              precision    recall  f1-score   support

           1       0.99      0.99      0.99      1332
           2       0.95      0.98      0.96      1389
           3       1.00      1.00      1.00      1290
           4       1.00      1.00      1.00      1336
           5       0.98      0.98      0.98      1302
           6       0.99      0.99      0.99      1340
           7       1.00      1.00      1.00      1305
           8       0.98      0.98      0.98      1319
           9       0.99      0.99      0.99      1325
          10       0.97      0.94      0.96      1343
          11       1.00      1.00      1.00      1346

    accuracy                           0.99     14627
   macro avg       0.99      0.99      0.99     14627
weighted avg       0.99      0.99      0.99     14627



In [43]:
#Classification report for the test data
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           1       0.99      1.00      0.99      1303
           2       0.95      0.97      0.96      1367
           3       1.00      1.00      1.00      1290
           4       1.00      1.00      1.00      1295
           5       0.98      0.97      0.98      1301
           6       0.99      0.98      0.99      1371
           7       1.00      1.00      1.00      1328
           8       0.98      0.98      0.98      1344
           9       0.99      0.99      0.99      1295
          10       0.97      0.95      0.96      1359
          11       1.00      1.00      1.00      1375

    accuracy                           0.98     14628
   macro avg       0.99      0.99      0.99     14628
weighted avg       0.98      0.98      0.98     14628



### Roc_auc scores for the svm non linear best model 

In [44]:

# roc auc score for training data
y_train_prob = best_non_linear.predict_proba(X_train)
print(f" The roc_auc score for the training data is {roc_auc_score(y_train,y_train_prob,average='weighted',multi_class='ovr')}")
# roc auc score for the validation data
y_valid_prob = best_non_linear.predict_proba(X_valid)
print(f" The roc_auc score for the validation data is {roc_auc_score(y_valid,y_valid_prob,average='weighted',multi_class='ovr')}")
# roc auc score for the testing data
y_test_prob = best_non_linear.predict_proba(X_test)
print(f" The roc_auc score for the testing data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The roc_auc score for the training data is 0.9999711530464098
 The roc_auc score for the validation data is 0.9997791927074581
 The roc_auc score for the testing data is 0.9997332562569385


### Recall score for the svm non linear best model 

In [45]:
# recall score for training data
print(f" The recall score for the training data is {recall_score(y_train,y_train_pred,average= 'macro')}")
# recall score for validation data
print(f" The recall score for the validation data is {recall_score(y_valid,y_valid_pred,average= 'macro')}")
# recall score for test data
print(f" The recall score for the testing data is {recall_score(y_test,y_test_pred,average= 'macro')}")

 The recall score for the training data is 0.9959833512542489
 The recall score for the validation data is 0.9861532848856643
 The recall score for the testing data is 0.9851186874234373


### f1-score for the best model 

In [46]:
# F-1 score for training data
print(f" The f-1 score for the training data is {f1_score(y_train,y_train_pred,average= 'weighted')}")
# F-1 score for validation data
print(f" The f-1 score for the validation data is {f1_score(y_valid,y_valid_pred,average= 'weighted')}")
# F-1 score for test data
print(f" The f-1 score for the testing data is {f1_score(y_test,y_test_pred,average= 'weighted')}")

 The f-1 score for the training data is 0.996034635570661
 The f-1 score for the validation data is 0.9860459040373616
 The f-1 score for the testing data is 0.9849551502008304


# classification  using Deep  Learning Model, Multi layer perceptron

In [16]:
# Importing the deep learning model
from sklearn.neural_network import MLPClassifier


In [12]:
# Taking random model
mlp = MLPClassifier()
#fitting random model with training data
mlp.fit(X_train,y_train)

C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [14]:
# finding accuracy for the random model
y_train_pred = mlp.predict(X_train)
y_valid_pred = mlp.predict(X_valid)
y_test_pred  = mlp.predict(X_test)

In [16]:
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred)}")
print(f" The validation data accuracy for the best model is {accuracy_score(y_valid,y_valid_pred)}")
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred)}")
      

 The training data accuracy for the best model is 0.9934026116086689
 The validation data accuracy for the best model is 0.9867368564982566
 The testing data accuracy for the best model is 0.9859174186491659


### Hyper parameter tuning for the model 

In [16]:
from sklearn.model_selection import RandomizedSearchCV
mlp = MLPClassifier()
# Define the parameter grid
param_grid = {
    'hidden_layer_sizes': [(100,), (200,), (500,), (1000,)],
    'activation': ['relu', 'logistic'],
    'solver': ['adam', 'sgd'],
    'alpha': [0.0001, 0.001, 0.01],
    'learning_rate': ['constant', 'adaptive'],
}

# Perform grid search cross-validation

clf = RandomizedSearchCV(mlp, param_grid, random_state=0)
clf.fit(X_train, y_train)


C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the opti

RandomizedSearchCV(estimator=MLPClassifier(),
                   param_distributions={'activation': ['relu', 'logistic'],
                                        'alpha': [0.0001, 0.001, 0.01],
                                        'hidden_layer_sizes': [(100,), (200,),
                                                               (500,),
                                                               (1000,)],
                                        'learning_rate': ['constant',
                                                          'adaptive'],
                                        'solver': ['adam', 'sgd']},
                   random_state=0)

In [17]:
# Print the best hyperparameters
print(f'Best hyperparameters: {clf.best_params_}')

Best hyperparameters: {'solver': 'adam', 'learning_rate': 'adaptive', 'hidden_layer_sizes': (500,), 'alpha': 0.001, 'activation': 'relu'}


In [17]:
# best model 
best_model_mlp =  MLPClassifier(solver= 'adam', learning_rate= 'adaptive', hidden_layer_sizes= (500,), alpha= 0.001, activation= 'relu')
best_model_mlp.fit(X_train,y_train)
file_name = 'mlp.sav'
pickle.dump(best_model_mlp,open(file_name,'wb'))

C:\Users\vasuk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


#### accuracies of the best model 

In [33]:
y_train_pred = best_model_mlp.predict(X_train)
y_valid_pred = best_model_mlp.predict(X_valid)
y_test_pred  = best_model_mlp.predict(X_test)
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred)}")
print(f" The validation data accuracy for the best model is {accuracy_score(y_valid,y_valid_pred)}")
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred)}")
      

 The training data accuracy for the best model is 0.9996239830450536
 The validation data accuracy for the best model is 0.9924796609010733
 The testing data accuracy for the best model is 0.9924801750068362


### confusion matrix for the best model 

In [21]:
### Training Data
print(confusion_matrix(y_train,y_train_pred))

[[2680    0    0    0    0    4    0    0    0    0    0]
 [   0 2562    0    0    0    0    0    0    0    1    0]
 [   0    0 2739    0    0    0    0    0    0    0    0]
 [   0    0    0 2688    0    0    0    0    0    0    0]
 [   0    0    0    0 2715    0    0    1    0    0    0]
 [   0    0    0    0    0 2607    0    0    1    0    0]
 [   0    0    0    0    0    0 2686    0    0    0    0]
 [   0    0    0    0    2    0    0 2654    0    0    0]
 [   0    0    0    0    0    1    0    0 2697    1    0]
 [   0    0    0    0    0    0    0    0    0 2617    0]
 [   0    0    0    0    0    0    0    0    0    0 2598]]


In [22]:
### validation Data
print(confusion_matrix(y_valid,y_valid_pred))

[[1319    0    0    0    0   13    0    0    0    0    0]
 [   0 1373    0    0    0    0    0    0    0   16    0]
 [   0    0 1285    0    4    0    0    0    1    0    0]
 [   0    0    0 1336    0    0    0    0    0    0    0]
 [   0    0    2    1 1288    0    0   11    0    0    0]
 [   2    0    0    0    0 1325    0    0   13    0    0]
 [   0    0    0    1    1    0 1303    0    0    0    0]
 [   0    0    0    1   10    0    0 1308    0    0    0]
 [   0    1    0    0    0    5    0    0 1318    1    0]
 [   0   27    0    0    0    0    0    0    0 1316    0]
 [   0    0    0    0    0    0    0    0    0    0 1346]]


In [23]:
### Testing Data
print(confusion_matrix(y_test,y_test_pred))

[[1294    0    0    0    0    8    0    0    1    0    0]
 [   0 1338    1    0    0    0    0    0    1   27    0]
 [   0    0 1285    0    3    0    0    0    1    1    0]
 [   0    0    0 1294    0    0    1    0    0    0    0]
 [   0    0    4    1 1284    0    0   12    0    0    0]
 [   5    0    0    0    0 1356    0    0   10    0    0]
 [   0    0    0    0    0    0 1328    0    0    0    0]
 [   0    0    0    1    8    0    0 1335    0    0    0]
 [   0    0    0    0    2    5    0    0 1287    1    0]
 [   0   17    0    0    0    0    0    0    0 1342    0]
 [   0    0    0    0    0    0    0    0    0    0 1375]]


### classification report for the best model 

In [24]:
#Classification report for the training data
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00      2684
           2       1.00      1.00      1.00      2563
           3       1.00      1.00      1.00      2739
           4       1.00      1.00      1.00      2688
           5       1.00      1.00      1.00      2716
           6       1.00      1.00      1.00      2608
           7       1.00      1.00      1.00      2686
           8       1.00      1.00      1.00      2656
           9       1.00      1.00      1.00      2699
          10       1.00      1.00      1.00      2617
          11       1.00      1.00      1.00      2598

    accuracy                           1.00     29254
   macro avg       1.00      1.00      1.00     29254
weighted avg       1.00      1.00      1.00     29254



In [25]:
#Classification report for the validation data
print(classification_report(y_valid,y_valid_pred))

              precision    recall  f1-score   support

           1       1.00      0.99      0.99      1332
           2       0.98      0.99      0.98      1389
           3       1.00      1.00      1.00      1290
           4       1.00      1.00      1.00      1336
           5       0.99      0.99      0.99      1302
           6       0.99      0.99      0.99      1340
           7       1.00      1.00      1.00      1305
           8       0.99      0.99      0.99      1319
           9       0.99      0.99      0.99      1325
          10       0.99      0.98      0.98      1343
          11       1.00      1.00      1.00      1346

    accuracy                           0.99     14627
   macro avg       0.99      0.99      0.99     14627
weighted avg       0.99      0.99      0.99     14627



In [26]:
#Classification report for the testing data
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           1       1.00      0.99      0.99      1303
           2       0.99      0.98      0.98      1367
           3       1.00      1.00      1.00      1290
           4       1.00      1.00      1.00      1295
           5       0.99      0.99      0.99      1301
           6       0.99      0.99      0.99      1371
           7       1.00      1.00      1.00      1328
           8       0.99      0.99      0.99      1344
           9       0.99      0.99      0.99      1295
          10       0.98      0.99      0.98      1359
          11       1.00      1.00      1.00      1375

    accuracy                           0.99     14628
   macro avg       0.99      0.99      0.99     14628
weighted avg       0.99      0.99      0.99     14628



#### ROC_auc_score for the best model 

In [27]:
# roc auc score for training data
y_train_prob = best_model_mlp.predict_proba(X_train)
print(f" The roc_auc score for the training data is {roc_auc_score(y_train,y_train_prob,average='weighted',multi_class='ovr')}")
# roc auc score for the validation data
y_valid_prob = best_model_mlp.predict_proba(X_valid)
print(f" The roc_auc score for the validation data is {roc_auc_score(y_valid,y_valid_prob,average='weighted',multi_class='ovr')}")
# roc auc score for the testing data
y_test_prob = best_model_mlp.predict_proba(X_test)
print(f" The roc_auc score for the testing data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The roc_auc score for the training data is 0.9999999204525996
 The roc_auc score for the validation data is 0.999881553251783
 The roc_auc score for the testing data is 0.9998939114561921


#### recall score for the best model 

In [28]:
# recall score for training data
print(f" The recall score for the training data is {recall_score(y_train,y_train_pred,average= 'macro')}")
# recall score for validation data
print(f" The recall score for the validation data is {recall_score(y_valid,y_valid_pred,average= 'macro')}")
# recall score for test data
print(f" The recall score for the testing data is {recall_score(y_test,y_test_pred,average= 'macro')}")

 The recall score for the training data is 0.9996248970843445
 The recall score for the validation data is 0.9925126357594057
 The recall score for the testing data is 0.9925308483209835


### f1-score for the best model 

In [29]:
# F-1 score for training data
print(f" The f-1 score for the training data is {f1_score(y_train,y_train_pred,average= 'weighted')}")
# F-1 score for validation data
print(f" The f-1 score for the validation data is {f1_score(y_valid,y_valid_pred,average= 'weighted')}")
# F-1 score for test data
print(f" The f-1 score for the testing data is {f1_score(y_test,y_test_pred,average= 'weighted')}")

 The f-1 score for the training data is 0.9996240106502341
 The f-1 score for the validation data is 0.9924817005460549
 The f-1 score for the testing data is 0.9924793773761309
